# VAEDecon Configuration File

data:
  data_dir: './datasets/'
  scaling_by_constant: true
  remove_low_var_genes: false
  force_reprocess: false
  # Training set, test set, and sct_gep_file (for finding true sampled GEPs).
  sct_file_path: [ './datasets/generated_sc_dataset_12ds_n_base100_all_subtypes/simu_bulk_exp_SCT_POS_N100_test_log2cpm1p.h5ad' ]
  simu_bulk_file_path: [ './datasets/simulated_bulk_cell_dataset_subtypes_all_range/segment_12ds_no_filtering_n_base100_median_gep/simu_bulk_exp_Mixed_N1K_segment_without_filtering_log2cpm1p.h5ad' ]
  test_sets:
    Test_set1:
      test_set_file_path: './datasets/simulated_bulk_cell_dataset_subtypes_all_range/segment_12ds_0.95_n_base100_19cancer_pca_0.9_median_gep/simu_bulk_exp_Test_set1_log2cpm1p.h5ad'
      sct_gep_file_path: './datasets/generated_sc_dataset_12ds_n_base100_all_subtypes/simu_bulk_exp_SCT_POS_N10K_log2cpm1p_25sct.h5ad'
      test_set_sample2cell_id_file_path: './datasets/simulated_bulk_cell_dataset_subtypes_all_range/segment_12ds_0.95_n_base100_19cancer_pca_0.9_median_gep/simu_bulk_exp_Test_set1_sampled_sc_cell_id.csv'
    Test_set2:
      test_set_file_path: './datasets/simulated_bulk_cell_dataset_subtypes_all_range/segment_12ds_alt_test/simu_bulk_exp_Test_set2_log2cpm1p.h5ad'
      sct_gep_file_path: './datasets/generated_sc_dataset_12ds_n_base100_all_subtypes/simu_bulk_exp_SCT_POS_N10K_log2cpm1p_25sct.h5ad'
      test_set_sample2cell_id_file_path: './datasets/simulated_bulk_cell_dataset_subtypes_all_range/segment_12ds_alt_test/simu_bulk_exp_Test_set2_sampled_sc_cell_id.csv'


training:
  output_dir: './output/vae'
  naming_postfix: 'my_experiment'
  learning_rate: 5.0e-5
  batch_size: 1024
  num_epochs: 1000
  n_early_stopping_patience: 15
  devices: 1
  device: 'auto'
  optimizer_cls: 'Adam'
  steps_saving: 0
  debug_model: false
  train_split: 0.8
  val_split: 0.2
  
  warmup_epochs: 50
  gene_stat_weight_schedule: "linear"
  gene_stat_weight_schedule_epochs: 50
  gene_mean_weight_start: 0.0
  gene_mean_weight_end: 0.0
  gene_std_weight_start: 0.0
  gene_std_weight_end: 0.0

  scheduler_cls: "WarmupReduceOnPlateau"
  scheduler_params:
    patience: 10
    factor: 0.5
    min_lr: 1.0e-7
    verbose: true


model:
  ppi_file_path: './datasets/PPI/format_h_sapiens.csv'
  input_dim: [1, 17834]
  latent_dim: 10
  n_cell_types: 16
  encoder_hidden_dims: [2048, 1024, 1024, 512]
  decoder_hidden_dims: [512, 1024, 1024, 2048]
  encoder_dropout_rate: [0, 0.1, 0.1, 0]
  decoder_dropout_rate: [0, 0.1, 0.1, 0]
  fusion_hidden_dims: [512, 256]
  fusion_dropout_rate: [0.1, 0]
  encoders: ['EncoderResMLP']
  decoders: ['DecoderResMLP']
  predict_cell_prop: false
  loss_coefficient:
    cell_prop: 0
    beta: 2
    gamma: 0.005
    kld_type: 'ave'
    weighting_gene_by_exp: true
    weight_clamp_range: [0.2, 5]
    gene_mean_weight: 0
    gene_std_weight: 0
    z_score_kl_weight: 1.0
  gnn_n_genes: 12596
  gnn_inter_col_dim: 500
  gnn_embd_col_dim: 30
  gnn_lambda_cols: 1.0
  gnn_num_layers: 3
  gnn_drop_p: 0.25
  gene_hidden_dim: 10
  gnn_topk_attention: 1024
  using_positional_encoding: false
  mask_ratio: 0.4


evaluation:
  n_samples: 3
  plot_cell_proportions: true
  plot_single_cell_gep: true
  plot_bulk_gep: true
  plot_latent_space: true
  n_neighbors: 15
  min_dist: 0.1
  figsize: [3.5, 3.5]
  rasterized: true
  show_metrics: true
  val_batch_size: 128
  figure_format: 'png'
  save_reconstructed_gep: false
  save_cell_type_specific_gep_metrics: false
  save_bulk_gep_input: true
  save_recon_bulk_gep_conv: true
  remove_low_var_genes: false
